# Workflow para construir e implantar um site Vite no GitHub Pages
name: Deploy Vite site to Pages

on:
  # Roda quando você faz uma alteração na branch `main`
  push:
    branches: ["main"]

  # Permite que você rode este workflow manualmente na aba Actions
  workflow_dispatch:

# Define as permissões que o robô precisa
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci # 'ci' é mais rápido e seguro que 'install' para robôs
      - name: Build
        # AQUI ESTÁ A MÁGICA FINAL - Nós passamos a variável que o seu vite.config.ts espera!
        run: npm run build
        env:
          VITE_BASE_PATH: /asperusmaia/ # Usando o nome EXATO do seu repositório
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Sobe o conteúdo da pasta 'dist' (o bolo pronto)
          path: './dist'

  # Job de deploy
  deploy:
    needs: build # Só roda depois que o 'build' terminar com sucesso
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
